ft_printf: src/complete_specifier/complete_specifier.c File Reference
complete_specifier.c File Reference
#include "ft_printf_private.h"
Functions
int complete_specifier_c (t_specifier *specif, void *data)
int complete_specifier_f (t_specifier *specif, void *data)
int complete_specifier_i (t_specifier *specif, void *data)
int complete_specifier_o (t_specifier *specif, void *data)
int complete_specifier_p (t_specifier *specif, void *data)
int complete_specifier_s (t_specifier *specif, void *data)
int complete_specifier_u (t_specifier *specif, void *data)
int complete_specifier_x (t_specifier *specif, void *data)
int complete_specifier_b (t_specifier *specif, void *data)
int complete_specifier (t_specifier *specif, void *data)
Function Documentation
complete_specifier()
int complete_specifier (t_specifier * specif, void * data)
Definition at line 25 of file complete_specifier.c.
References complete_specifier_b(), complete_specifier_c(), complete_specifier_f(), complete_specifier_i(), complete_specifier_o(), complete_specifier_p(), complete_specifier_s(), complete_specifier_u(), complete_specifier_x(), and s_specifier::formatid.
complete_specifier_b()
int complete_specifier_b (t_specifier * specif, void * data)
Definition at line 15 of file complete_specifier_b.c.
References get_ndigits_ll(), s_optional::isgiven, min(), s_specifier::npad_precision, s_specifier::npad_width, s_specifier::plus, s_specifier::precision, s_specifier::space, s_optional::value, and s_specifier::width.
complete_specifier_c()
int complete_specifier_c (t_specifier * specif, void * data)
Definition at line 15 of file complete_specifier_c.c.
References s_optional::isgiven, min(), s_specifier::npad_width, s_optional::value, and s_specifier::width.
complete_specifier_f()
int complete_specifier_f (t_specifier * specif, void * data)
Definition at line 42 of file complete_specifier_f.c.
References s_optional::isgiven, isnan, s_specifier::precision, and s_optional::value.
complete_specifier_i()
int complete_specifier_i (t_specifier * specif, void * data)
Definition at line 15 of file complete_specifier_i.c.
References get_ndigits_ll(), s_optional::isgiven, min(), s_specifier::npad_precision, s_specifier::npad_width, s_specifier::plus, s_specifier::precision, s_specifier::space, s_optional::value, and s_specifier::width.
complete_specifier_o()
int complete_specifier_o (t_specifier * specif, void * data)
Definition at line 15 of file complete_specifier_o.c.
References get_ndigits_ull(), s_specifier::hash, s_optional::isgiven, min(), s_specifier::npad_precision, s_specifier::npad_width, s_specifier::precision, s_optional::value, and s_specifier::width.
complete_specifier_p()
int complete_specifier_p (t_specifier * specif, void * data)
Definition at line 15 of file complete_specifier_p.c.
References get_ndigits_ull(), s_optional::isgiven, min(), s_specifier::npad_precision, s_specifier::npad_width, s_specifier::precision, s_optional::value, and s_specifier::width.
complete_specifier_s()
int complete_specifier_s (t_specifier * specif, void * data)
Definition at line 15 of file complete_specifier_s.c.
References ft_strlen(), s_optional::isgiven, min(), s_specifier::npad_width, s_specifier::precision, s_optional::value, and s_specifier::width.
complete_specifier_u()
int complete_specifier_u (t_specifier * specif, void * data)
Definition at line 15 of file complete_specifier_u.c.
References get_ndigits_ull(), s_optional::isgiven, min(), s_specifier::npad_precision, s_specifier::npad_width, s_specifier::precision, s_optional::value, and s_specifier::width.
complete_specifier_x()
int complete_specifier_x (t_specifier * specif, void * data)
Definition at line 15 of file complete_specifier_x.c.
References get_ndigits_ull(), s_specifier::hash, s_optional::isgiven, min(), s_specifier::npad_precision, s_specifier::npad_width, s_specifier::precision, s_optional::value, and s_specifier::width.