ft_printf: src/fetch_data/fetch_data.c File Reference
fetch_data.c File Reference
#include "ft_printf_private.h"
Functions
int fetch_data_c (t_specifier *specif, void **data, va_list ap)
int fetch_data_f (t_specifier *specif, void **data, va_list ap)
int fetch_data_i (t_specifier *specif, void **data, va_list ap)
int fetch_data_p (t_specifier *specif, void **data, va_list ap)
int fetch_data_pc (t_specifier *specif, void **data, va_list ap)
int fetch_data_s (t_specifier *specif, void **data, va_list ap)
int fetch_data_u (t_specifier *specif, void **data, va_list ap)
int fetch_data (t_specifier *specif, void **data, va_list ap)
Function Documentation
fetch_data()
int fetch_data (t_specifier * specif, void ** data, va_list ap)
Definition at line 23 of file fetch_data.c.
References fetch_data_c(), fetch_data_f(), fetch_data_i(), fetch_data_p(), fetch_data_pc(), fetch_data_s(), fetch_data_u(), and s_specifier::formatid.
fetch_data_c()
int fetch_data_c (t_specifier * specif, void ** data, va_list ap)
Definition at line 15 of file fetch_data_c.c.
fetch_data_f()
int fetch_data_f (t_specifier * specif, void ** data, va_list ap)
Definition at line 15 of file fetch_data_f.c.
References L, l, s_specifier::length, and NONE.
fetch_data_i()
int fetch_data_i (t_specifier * specif, void ** data, va_list ap)
Definition at line 15 of file fetch_data_i.c.
References h, hh, l, s_specifier::length, ll, and NONE.
fetch_data_p()
int fetch_data_p (t_specifier * specif, void ** data, va_list ap)
Definition at line 15 of file fetch_data_p.c.
fetch_data_pc()
int fetch_data_pc (t_specifier * specif, void ** data, va_list ap)
Definition at line 15 of file fetch_data_pc.c.
fetch_data_s()
int fetch_data_s (t_specifier * specif, void ** data, va_list ap)
Definition at line 15 of file fetch_data_s.c.
fetch_data_u()
int fetch_data_u (t_specifier * specif, void ** data, va_list ap)
Definition at line 15 of file fetch_data_u.c.
References h, hh, l, s_specifier::length, ll, and NONE.