ft_printf: src/ft_printf_private.h File Reference
ft_printf_private.h File Reference
#include <stdarg.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include "libft.h"
Data Structures
struct s_buffer
struct s_optional
struct s_specifier
Macros
#define BUFFER_SIZE 1024
#define KNRM "\x1B[0m"
#define KRED "\x1B[31m"
#define KGRN "\x1B[32m"
#define KYEL "\x1B[33m"
#define KBLU "\x1B[34m"
#define KMAG "\x1B[35m"
#define KCYN "\x1B[36m"
Typedefs
typedef struct s_buffer t_buffer
typedef enum e_length t_length
typedef struct s_optional t_optional
typedef struct s_specifier t_specifier
Enumerations
enum e_length {
h, l, hh, ll,
L, NONE
}
Functions
int ft_vprintf (const char *format, va_list ap)
Replicates behaviour of vprintf(3).
int ft_vdprintf (int fd, const char *format, va_list ap)
Replicates behaviour of vdprintf(3).
int ft_printf (const char *format,...)
Replicates behaviour of printf(3).
int ft_dprintf (int fd, const char *format,...)
Replicates behaviour of dprintf(3).
int parse_specifier (t_specifier *specif, const char **format, va_list ap)
int validate_specifier (t_specifier *specif)
int fetch_data (t_specifier *specif, void **data, va_list ap)
int complete_specifier (t_specifier *specif, void *data)
int print_data (t_specifier *specif, void *data)
size_t buffered_putchar (char c)
size_t buffered_puts (const char *str)
size_t buffered_putnchar (char c, size_t n)
void set_fd (int fd)
int get_fd (void)
void cleanup_buffer (void)
size_t flush_buffer (void)
size_t min (size_t a, size_t b)
size_t get_ndigits_ll (long long num, size_t base_len)
size_t get_ndigits_ull (unsigned long long num, size_t base_len)
int print_digits_ll (long long num, char *radix)
int print_digits_ull (unsigned long long num, char *radix)
int print_digits_lf (long double num, char *radix, size_t precision, int print_dot)
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE 1024
Definition at line 23 of file ft_printf_private.h.
KBLU
#define KBLU "\x1B[34m"
Definition at line 29 of file ft_printf_private.h.
KCYN
#define KCYN "\x1B[36m"
Definition at line 31 of file ft_printf_private.h.
KGRN
#define KGRN "\x1B[32m"
Definition at line 27 of file ft_printf_private.h.
KMAG
#define KMAG "\x1B[35m"
Definition at line 30 of file ft_printf_private.h.
KNRM
#define KNRM "\x1B[0m"
Definition at line 25 of file ft_printf_private.h.
KRED
#define KRED "\x1B[31m"
Definition at line 26 of file ft_printf_private.h.
KYEL
#define KYEL "\x1B[33m"
Definition at line 28 of file ft_printf_private.h.
Typedef Documentation
t_buffer
typedef struct s_buffer t_buffer
t_length
typedef enum e_length t_length
t_optional
typedef struct s_optional t_optional
t_specifier
typedef struct s_specifier t_specifier
Enumeration Type Documentation
e_length
enum e_length
Enumerator
h
l
hh
ll
L
NONE
Definition at line 39 of file ft_printf_private.h.
Function Documentation
buffered_putchar()
size_t buffered_putchar (char c)
utils
Definition at line 43 of file buffered_putchar.c.
buffered_putnchar()
size_t buffered_putnchar (char c, size_t n)
Definition at line 15 of file buffered_putnchar.c.
References buffered_putchar().
buffered_puts()
size_t buffered_puts (const char * str)
Definition at line 15 of file buffered_puts.c.
References buffered_putchar().
cleanup_buffer()
void cleanup_buffer (void)
Definition at line 29 of file buffered_putchar.c.
complete_specifier()
int complete_specifier (t_specifier * specif, void * data)
Definition at line 25 of file complete_specifier.c.
References complete_specifier_b(), complete_specifier_c(), complete_specifier_f(), complete_specifier_i(), complete_specifier_o(), complete_specifier_p(), complete_specifier_s(), complete_specifier_u(), complete_specifier_x(), and s_specifier::formatid.
fetch_data()
int fetch_data (t_specifier * specif, void ** data, va_list ap)
Definition at line 23 of file fetch_data.c.
References fetch_data_c(), fetch_data_f(), fetch_data_i(), fetch_data_p(), fetch_data_pc(), fetch_data_s(), fetch_data_u(), and s_specifier::formatid.
flush_buffer()
size_t flush_buffer (void)
Definition at line 36 of file buffered_putchar.c.
get_fd()
int get_fd (void)
Definition at line 19 of file buffered_putchar.c.
get_ndigits_ll()
size_t get_ndigits_ll (long long num, size_t base_len)
Definition at line 15 of file get_ndigits_ll.c.
get_ndigits_ull()
size_t get_ndigits_ull (unsigned long long num, size_t base_len)
Definition at line 15 of file get_ndigits_ull.c.
min()
size_t min (size_t a, size_t b) inline
Definition at line 15 of file min.c.
parse_specifier()
int parse_specifier (t_specifier * specif, const char ** format, va_list ap)
dispatchers
Definition at line 96 of file parse_specifier.c.
print_data()
int print_data (t_specifier * specif, void * data)
Definition at line 26 of file print_data.c.
References s_specifier::formatid, print_data_b(), print_data_c(), print_data_f(), print_data_i(), print_data_o(), print_data_p(), print_data_s(), print_data_u(), print_data_x(), and print_data_xx().
print_digits_lf()
int print_digits_lf (long double num, char * radix, size_t precision, int print_dot)
Definition at line 25 of file print_digits_lf.c.
print_digits_ll()
int print_digits_ll (long long num, char * radix)
Definition at line 15 of file print_digits_ll.c.
References buffered_putchar(), and ft_strlen().
print_digits_ull()
int print_digits_ull (unsigned long long num, char * radix)
Definition at line 15 of file print_digits_ull.c.
References buffered_putchar(), and ft_strlen().
set_fd()
void set_fd (int fd)
Definition at line 24 of file buffered_putchar.c.
validate_specifier()
int validate_specifier (t_specifier * specif)
Definition at line 24 of file validate_specifier.c.
References s_specifier::formatid, validate_specifier_b(), validate_specifier_c(), validate_specifier_f(), validate_specifier_i(), validate_specifier_p(), validate_specifier_s(), validate_specifier_u(), and validate_specifier_x().