ft_printf: test/functional/src/main.c File Reference
main.c File Reference
#include <unistd.h>
#include <stdio.h>
#include "unity.h"
#include "ft_printf.h"
Functions
void setUp (void)
void tearDown (void)
void test_output (const char *expected, const char *format,...)
void test_rc (int expected, const char *format,...)
void test_basic (void)
void test_pc (void)
void test_x (void)
void test_xx (void)
void test_s (void)
void test_c (void)
void test_o (void)
void test_d (void)
void test_u (void)
void test_f (void)
void test_asterix (void)
void test_b (void)
void test_colors (void)
int main (void)
Function Documentation
main()
int main (void)
Definition at line 355 of file main.c.
References RUN_TEST, test_asterix(), test_b(), test_basic(), test_c(), test_colors(), test_d(), test_f(), test_o(), test_pc(), test_s(), test_u(), test_x(), test_xx(), UNITY_BEGIN, and UNITY_END.
setUp()
void setUp (void)
Definition at line 18 of file main.c.
tearDown()
void tearDown (void)
Definition at line 23 of file main.c.
test_asterix()
void test_asterix (void)
Definition at line 331 of file main.c.
References test_output().
test_b()
void test_b (void)
Definition at line 337 of file main.c.
References test_output().
test_basic()
void test_basic (void)
Definition at line 65 of file main.c.
References test_output().
test_c()
void test_c (void)
Definition at line 162 of file main.c.
References test_output().
test_colors()
void test_colors (void)
Definition at line 344 of file main.c.
References test_output(), and test_rc().
test_d()
void test_d (void)
Definition at line 191 of file main.c.
References test_output().
test_f()
void test_f (void)
Definition at line 289 of file main.c.
References l, and test_output().
test_o()
void test_o (void)
Definition at line 169 of file main.c.
References test_output().
test_output()
void test_output (const char * expected, const char * format, ...)
Definition at line 28 of file main.c.
References ft_vdprintf(), and TEST_ASSERT_EQUAL_STRING_MESSAGE.
test_pc()
void test_pc (void)
Definition at line 74 of file main.c.
References test_output().
test_rc()
void test_rc (int expected, const char * format, ...)
Definition at line 48 of file main.c.
References ft_vdprintf(), and TEST_ASSERT_EQUAL_MESSAGE.
test_s()
void test_s (void)
Definition at line 122 of file main.c.
References test_output().
test_u()
void test_u (void)
Definition at line 270 of file main.c.
References test_output().
test_x()
void test_x (void)
Definition at line 84 of file main.c.
References test_output().
test_xx()
void test_xx (void)
Definition at line 111 of file main.c.
References test_output().