ft_printf: src/print_data/print_data.c File Reference
print_data.c File Reference
#include "ft_printf_private.h"
Functions
int print_data_c (t_specifier *specif, void *data)
int print_data_f (t_specifier *specif, void *data)
int print_data_i (t_specifier *specif, void *data)
int print_data_o (t_specifier *specif, void *data)
int print_data_p (t_specifier *specif, void *data)
int print_data_s (t_specifier *specif, void *data)
int print_data_u (t_specifier *specif, void *data)
int print_data_x (t_specifier *specif, void *data)
int print_data_xx (t_specifier *specif, void *data)
int print_data_b (t_specifier *specif, void *data)
int print_data (t_specifier *specif, void *data)
Function Documentation
print_data()
int print_data (t_specifier * specif, void * data)
Definition at line 26 of file print_data.c.
References s_specifier::formatid, print_data_b(), print_data_c(), print_data_f(), print_data_i(), print_data_o(), print_data_p(), print_data_s(), print_data_u(), print_data_x(), and print_data_xx().
print_data_b()
int print_data_b (t_specifier * specif, void * data)
Definition at line 81 of file print_data_b.c.
References s_specifier::minus.
print_data_c()
int print_data_c (t_specifier * specif, void * data)
Definition at line 15 of file print_data_c.c.
References buffered_putchar(), buffered_putnchar(), s_specifier::minus, and s_specifier::npad_width.
print_data_f()
int print_data_f (t_specifier * specif, void * data)
Definition at line 89 of file print_data_f.c.
References isnan.
print_data_i()
int print_data_i (t_specifier * specif, void * data)
Definition at line 79 of file print_data_i.c.
References s_specifier::minus.
print_data_o()
int print_data_o (t_specifier * specif, void * data)
Definition at line 77 of file print_data_o.c.
References s_specifier::minus.
print_data_p()
int print_data_p (t_specifier * specif, void * data)
Definition at line 66 of file print_data_p.c.
References s_specifier::minus.
print_data_s()
int print_data_s (t_specifier * specif, void * data)
Definition at line 24 of file print_data_s.c.
print_data_u()
int print_data_u (t_specifier * specif, void * data)
Definition at line 67 of file print_data_u.c.
References s_specifier::minus.
print_data_x()
int print_data_x (t_specifier * specif, void * data)
Definition at line 78 of file print_data_x.c.
References s_specifier::minus.
print_data_xx()
int print_data_xx (t_specifier * specif, void * data)
Definition at line 78 of file print_data_xx.c.
References s_specifier::minus.