ft_printf: src/validate_specifier/validate_specifier.c File Reference
validate_specifier.c File Reference
#include "ft_printf_private.h"
Functions
int validate_specifier_c (t_specifier *specif)
int validate_specifier_f (t_specifier *specif)
int validate_specifier_i (t_specifier *specif)
int validate_specifier_p (t_specifier *specif)
int validate_specifier_s (t_specifier *specif)
int validate_specifier_u (t_specifier *specif)
int validate_specifier_x (t_specifier *specif)
int validate_specifier_b (t_specifier *specif)
int validate_specifier (t_specifier *specif)
Function Documentation
validate_specifier()
int validate_specifier (t_specifier * specif)
Definition at line 24 of file validate_specifier.c.
References s_specifier::formatid, validate_specifier_b(), validate_specifier_c(), validate_specifier_f(), validate_specifier_i(), validate_specifier_p(), validate_specifier_s(), validate_specifier_u(), and validate_specifier_x().
validate_specifier_b()
int validate_specifier_b (t_specifier * specif)
Definition at line 15 of file validate_specifier_b.c.
References s_specifier::hash, s_optional::isgiven, L, s_specifier::length, s_specifier::minus, s_specifier::plus, s_specifier::precision, s_specifier::space, s_specifier::width, and s_specifier::zero.
validate_specifier_c()
int validate_specifier_c (t_specifier * specif)
Definition at line 15 of file validate_specifier_c.c.
References s_specifier::hash, s_optional::isgiven, s_specifier::length, NONE, s_specifier::plus, s_specifier::precision, s_specifier::space, and s_specifier::zero.
validate_specifier_f()
int validate_specifier_f (t_specifier * specif)
Definition at line 15 of file validate_specifier_f.c.
References s_optional::isgiven, l, L, s_specifier::length, s_specifier::minus, NONE, s_specifier::plus, s_specifier::precision, s_specifier::space, s_optional::value, s_specifier::width, and s_specifier::zero.
validate_specifier_i()
int validate_specifier_i (t_specifier * specif)
Definition at line 15 of file validate_specifier_i.c.
References s_specifier::hash, s_optional::isgiven, L, s_specifier::length, s_specifier::minus, s_specifier::plus, s_specifier::precision, s_specifier::space, s_specifier::width, and s_specifier::zero.
validate_specifier_p()
int validate_specifier_p (t_specifier * specif)
Definition at line 15 of file validate_specifier_p.c.
References s_specifier::hash, s_optional::isgiven, s_specifier::length, s_specifier::minus, NONE, s_specifier::plus, s_specifier::precision, s_specifier::space, s_specifier::width, and s_specifier::zero.
validate_specifier_s()
int validate_specifier_s (t_specifier * specif)
Definition at line 15 of file validate_specifier_s.c.
References s_specifier::hash, s_specifier::length, NONE, s_specifier::plus, s_specifier::space, and s_specifier::zero.
validate_specifier_u()
int validate_specifier_u (t_specifier * specif)
Definition at line 15 of file validate_specifier_u.c.
References s_specifier::hash, s_optional::isgiven, L, s_specifier::length, s_specifier::minus, s_specifier::plus, s_specifier::precision, s_specifier::space, s_specifier::width, and s_specifier::zero.
validate_specifier_x()
int validate_specifier_x (t_specifier * specif)
Definition at line 15 of file validate_specifier_x.c.
References s_optional::isgiven, L, s_specifier::length, s_specifier::minus, s_specifier::plus, s_specifier::precision, s_specifier::space, s_specifier::width, and s_specifier::zero.